spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xx.xx.xx.xx:3306/api_runner?autoReconnect=true&useUnicode=true&serverTimezone=UTC
    username: xxxxx
    password: xxxxxx!@#


    #邮件报告中大饼图图片存放本地路径
pic_path: /Users/pic/dabing.png

#maven仓库
nexus-address: http://http://XXX.XX.XX.X/:8081/repository/

#jar包本地存放路径,可自定义存放路径
nexus-target: server/src/main/resources/lib/

#本地是否开启redis和zk代理
open_ssh: false